networks:
  mela-net:

services:
  backend:
    container_name: mela.app.backend
    restart: always
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app/
      - /app/node_modules
      - /app/generated/prisma
      - /app/dist
      - ./var/logs/backend:/tmp/logs
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://backend:3000/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    expose:
      - "3000"
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mela-net
