version: '3'

services:
  nx-app-base-dev:
    restart: always
    build:
      context: .
      dockerfile: $PWD/docker/dev/Dockerfile
      target: node-dev
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
      - /app/node_modules
  nginx:
    restart: always
#    build:
#      context: .
#      dockerfile: $PWD/docker/dev/Dockerfile
#      target: node-dev
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./docker/dev/nginx:/etc/nginx/templates
      - /app/node_modules
  database:
    image: postgres:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
