# This docker file is to run against test database

version: '4'

services:

  frontend:
    container_name: mela.app.frontend
    extends:
      file: docker-compose-prod.base.yml
      service: nx-app-base-dev
    build:
      target: mela-frontend
    ports:
      - "9000:9000"
    environment:
      - KEYCLOAK_HOST=$KEYCLOAK_HOST
      - KEYCLOAK_REALM=$KEYCLOAK_REALM
      - KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
