version: '3'

services:

  nx-app-base-dev:
    restart: always
    build:
      context: .
      dockerfile: $PWD/Dockerfile
      target: node-dev
    volumes:
      - ./libs:/app/libs
      - ./apps:/app/apps
      - ./docker:/app/docker
      - ./link:/app/link
      - ./prisma:/app/prisma
      - /app/generated
      - /app/node_modules