version: '3'

services:
  nx-app-base-dev:
    #    tty: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: $PWD/docker/dev/Dockerfile
      target: node-dev
    volumes:
      - ./:/app
      - /app/node_modules
  database:
    image: postgres:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
