name: "Setup"
description: "Load node cache"

runs:
  using: "composite"
  steps:
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('pnpm-lock.yaml') }}
    - uses: pnpm/action-setup@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        registry-url: https://registry.npmjs.org/
        scope: "@ghentcdh"
    - name: Set Directory as Safe
      run: |
        git config --system --add safe.directory "$GITHUB_WORKSPACE"
      shell: bash

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4

    - run: |
        echo "BASE: ${{ env.NX_BASE }}"
        echo "HEAD: ${{ env.NX_HEAD }}"
