name: "Login docker"

runs:
  using: "composite"
  steps:
    - name: Extract version and set it to TAG env var
      run: |
        echo "TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV
        echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      shell: bash
    - name: Use the tag
      run: echo "The latest tag is ${{ env.TAG }}"
      shell: bash
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3