name: "Login docker"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Extract version and set it to TAG env var
      run: |
        echo "TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV
        echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Use the tag
      run: echo "The latest tag is ${{ env.TAG }}"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}