<template>
  <Menu title="Elements" :menu="menuElements" :breadcrumbs="breadcrumbs" />

  <div v-if="textStore.text" class="mt-2">
    <annotate-text
      :store-id="storeId"
      @save-example="saveExample"
      @save-annotation="saveAnnotation"
      @close-annotation="closeAnnotation"
      @delete-annotation="deleteAnnotation"
    />
  </div>
  <div v-if="modeToast" class="toast toast-center">
    <div role="alert" class="alert alert-success bg-white">
      <span>{{ modeToast.text }}</span>
      <div class="flex gap-2">
        <Btn
          v-if="modeToast.deny"
          :color="Color.secondary"
          @click="modeToast.deny"
        >
          Close
        </Btn>
        <Btn v-if="modeToast.save" @click="modeToast.save"> Save</Btn>
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import type { ExampleDto } from '@mela/text/shared';
import { computed, effect, ref } from 'vue';

import type { W3CAnnotation } from '@ghentcdh/annotations/core';
import { Btn, Color, Menu } from '@ghentcdh/ui';

import AnnotateText from './controls/annotate-text/annotate-text.vue';
import type { MODES } from './controls/annotate-text/props';
import { useModeStore } from './controls/annotate-text/store/mode.store';
import { useAnnotationStore } from './controls/annotate-text/utils/annotation.store';
import { useTextStore } from './text.store';

const textStore = useTextStore();
const storeId = 'identify_and_translate' + Date.now();

const annotationStore = useAnnotationStore(storeId);
const modeStore = useModeStore();
const generatedBlocks = ref(false);

const menuElements = computed(() => {
  return [
    {
      label: 'Elements',
      items: [
        textStore.sources.map((s) => ({
          label: `Generate blocks ${s.text_type}`,
          action: () => generateBlocks(s.id),
        })),
        {
          label: 'Create annotation',
          action: () => createAnnotation(),
        },
      ].flat(),
    },
  ];
});

const breadcrumbs = computed(() => {
  return textStore.text
    ? [
        {
          label: 'Texts',
          routerLink: 'text-index',
        },
        {
          label: `${textStore.text.name} (${textStore.text.author?.name})`,
        },
        modeStore.activeMode
          ? {
              label: modeStore.activeMode,
            }
          : null,
      ].filter((m) => !!m)
    : [];
});

const modeToasts: Record<
  MODES,
  { deny?: () => void; save?: () => void; text: string }
> = {
  'create-annotation': {
    deny: () => modeStore.resetMode(),
    text: 'Create new annotation by selecting text',
  },
  generate: {
    save: () => saveGeneratedBlocks(),
    deny: () => cancelGeneratedBlocks(),
    text: 'The autogenerated blocks are not saved',
  },
  edit: {
    deny: () => {
      closeAnnotation();
    },
    text: 'Edit mode is on',
  },
};

const modeToast = computed(() =>
  modeStore.activeMode ? modeToasts[modeStore.activeMode] : null,
);

effect(() => {
  if (!textStore.text) return;
  annotationStore.init(textStore.sources, textStore.textId);
});

const generateBlocks = (sourceId: string) => {
  modeStore.changeMode('generate', () => {
    annotationStore.autoGenerateBlocks(sourceId);
    generatedBlocks.value = true;
  });
};

const saveGeneratedBlocks = () => {
  annotationStore.selectAnnotation(null);
  annotationStore.saveGeneratedBlocks();
  generatedBlocks.value = false;
  modeStore.resetMode();
};

const cancelGeneratedBlocks = () => {
  annotationStore.cancelGeneratedBLocks();
  generatedBlocks.value = false;
  modeStore.resetMode();
};

const createAnnotation = () => {
  modeStore.changeMode('create-annotation', () => {
    annotationStore.selectAnnotation(null);
    // cancelGeneratedBlocks();
  });
};

const saveAnnotation = (annotation: W3CAnnotation) => {
  annotationStore.saveOrCreateAnnotation(annotation);
};

const saveExample = (example: ExampleDto) => {
  annotationStore.saveExample(example);
};

const deleteAnnotation = (annotation: W3CAnnotation) => {
  annotationStore.deleteAnnotation(annotation.id);
  closeAnnotation();
};

const closeAnnotation = () => {
  annotationStore.reloadFromTextWithAnnotations();
  annotationStore.selectAnnotation(null);

  modeStore.resetMode();
};
</script>
