<template>
  <div class="navbar bg-base-100 shadow-sm">
    <div class="flex-1">
      <div class="breadcrumbs text-sm">
        <ul v-if="textStore.text">
          <li><a>Texts</a></li>
          <li>{{ textStore.text.name }} ({{ textStore.text.author?.name }})</li>
          <li v-if="modeStore.activeMode">
            {{ modeStore.activeMode }}
          </li>
        </ul>
      </div>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1">
        <li>
          <details>
            <summary>Elements</summary>
            <ul class="bg-base-100 rounded-t-none p-2">
              <li
                v-for="source in textStore.sources"
                :key="source.id"
              >
                <button @click="generateBlocks(source.id)">
                  Auto generate text blocks:
                  {{ source.text_type }}
                </button>
              </li>
              <li>
                <button @click="createAnnotation">
                  Create annotation
                </button>
              </li>
            </ul>
          </details>
        </li>
        <li>
          <details>
            <summary>Display</summary>
            <ul class="bg-base-100 rounded-t-none p-2">
              TODO add display options
              <li><a>Link 1</a></li>
              <li><a>Link 2</a></li>
            </ul>
          </details>
        </li>
      </ul>
    </div>
  </div>
  <div v-if="textStore.text">
    <annotate-text
      :store-id="storeId"
      @save-annotation="saveAnnotation"
      @close-annotation="closeAnnotation"
    />
  </div>
  <div
    v-if="modeToast"
    class="toast toast-center"
  >
    <div
      role="alert"
      class="alert alert-success bg-white"
    >
      <span>{{ modeToast.text }}</span>
      <div class="flex gap-2">
        <Btn
          v-if="modeToast.deny"
          :color="Color.secondary"
          @click="modeToast.deny"
        >
          Deny
        </Btn>
        <Btn
          v-if="modeToast.save"
          @click="modeToast.save"
        >
          Save
        </Btn>
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import { computed, effect, ref } from 'vue';

import type { W3CAnnotation } from '@ghentcdh/annotations/core';
import { Btn, Color } from '@ghentcdh/ui';

import AnnotateText from './controls/annotate-text/annotate-text.vue';
import type { MODES } from './controls/annotate-text/props';
import { useModeStore } from './controls/annotate-text/store/mode.store';
import { useAnnotationStore } from './controls/annotate-text/utils/annotation.store';
import { useTextStore } from './text.store';

const textStore = useTextStore();
const storeId = 'identify_and_translate' + Date.now();

const annotationStore = useAnnotationStore(storeId);
const modeStore = useModeStore();
const generatedBlocks = ref(false);

const modeToasts: Record<
  MODES,
  { deny?: () => void; save?: () => void; text: string }
> = {
  'create-annotation': {
    text: 'Create new annotation by selecting text',
  },
  generate: {
    save: () => saveGeneratedBlocks(),
    deny: () => cancelGeneratedBlocks(),
    text: 'The autogenerated blocks are not saved',
  },
  edit: {
    text: 'Edit mode is on',
  },
};

const modeToast = computed(() =>
  modeStore.activeMode ? modeToasts[modeStore.activeMode] : null,
);

effect(() => {
  if (!textStore.text) return;
  annotationStore.init(textStore.sources, textStore.textId);
});

const generateBlocks = (sourceId: string) => {
  modeStore.changeMode('generate', () => {
    annotationStore.autoGenerateBlocks(sourceId);
    generatedBlocks.value = true;
  });
};

const saveGeneratedBlocks = () => {
  annotationStore.selectAnnotation(null);
  annotationStore.saveGeneratedBlocks();
  generatedBlocks.value = false;
  modeStore.resetMode();
};

const cancelGeneratedBlocks = () => {
  annotationStore.cancelGeneratedBLocks();
  generatedBlocks.value = false;
  modeStore.resetMode();
};

const createAnnotation = () => {
  modeStore.changeMode('create-annotation', () => {
    annotationStore.selectAnnotation(null);
    // cancelGeneratedBlocks();
  });
};

const saveAnnotation = (annotation: W3CAnnotation) => {
  annotationStore.saveOrCreateAnnotation(annotation).then(() => {
    closeAnnotation();
  });
};

const closeAnnotation = () => {
  annotationStore.reloadFromTextWithAnnotations();
  annotationStore.selectAnnotation(null);

  modeStore.resetMode();
};
</script>
