name: Docker build

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  docker-publish-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            version=${{ env.TAG }}
          target: mela-frontend
          tags: |
            ghentcdh/mela-frontend:latest
            ghentcdh/mela-frontend:${{ env.TAG }}
  docker-publish-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          target: mela-backend
          push: true
          tags: |
            ghentcdh/mela-backend:latest
            ghentcdh/mela-backend:${{ env.TAG }}
