name: Docker build

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract version and set it to TAG env var
        run: |
          echo "TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: mela-frontend
          tags: |
            ghentcdh/mela-frontend:latest
            ghentcdh/mela-frontend:${{ env.TAG }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: mela-backend
          push: true
          tags: |
            ghentcdh/mela-backend:latest
            ghentcdh/mela-backend:${{ env.TAG }}