name: Docker build

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  docker-prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag is $latest_tag"
          echo "TAG=$latest_tag" >> $GITHUB_ENV
      - name: Use the tag
        run: echo "The latest tag is ${{ env.TAG }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: mela-frontend
          tags: |
            ghentcdh/mela-frontend:latest
            ghentcdh/mela-frontend:${{ env.TAG }}
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          target: mela-backend
          push: true
          tags: |
            ghentcdh/mela-backend:latest
            ghentcdh/mela-backend:${{ env.TAG }}